# Generated by Django 5.2.1 on 2025-05-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='monto_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
