# Generated by Django 5.2.1 on 2025-05-16 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0002_categoria_monto_max'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='monto_max',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, to='finanzas_app.categoria'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UsuarioCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas_app.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'categoria')},
            },
        ),
    ]
